export const personalidades = [
    "Inabalável", "Trapaceiro", "Introvertido", "Carismático", "Servo", "Indeciso", "Procrastinador", "Imparcial", 
    "Modesto", "Corajoso", "Valente", "Tímido", "Gentil", "Atencioso", "Irritadiço", "Patriota", "Indiferente", 
    "Sonolento", "Apostador", "Esportista", "Sociopata", "Estranho", "Espalhafatoso", "Idol", "Simplista", "Sério", 
    "Diligente", "Calmo", "Justiça", "Franqueza", "Amizade", "Companheirismo", "Questionador", "Criativo", 
    "Protetor", "Atrapalhado", "Aproveitador", "Fofoqueiro", "Anti-social", "Apaixonado", "Calado", "Traíra", 
    "Narcisista", "Competidor", "Pacifista", "Compreensivo", "Gosto caro", "Briguento", "Preguiçoso", "Força da natureza", 
    "Precipitado", "Inocente", "Altruísta", "Herói", "Alegre", "Humilde", "Castrado", "Honesto", "Dedicado", "Derrotista", 
    "Falador", "Paquerador", "Palhaço", "Provocador", "Líder", "Amável", "Honrado", "Precavido", "Audacioso", "Respeitoso", 
    "Teimoso", "Distraído", "Inquieto", "Antipático", "Crente", "Mentiroso", "Invejoso", "Ganancioso", "Orgulhoso", 
    "Malicioso", "Fervoroso", "Guloso", "Ingrato", "Hipócrita", "Exibicionista", "Exigente", "Estudioso", "Hospitaleiro", 
    "Mal educado", "Paladar exótico", "Companheiro", "Complexo de inferioridade", "Infantil", "Amante da natureza", 
    "Inseguro", "poucas palavras"
];

export const zeus = [
    {
        imagem: "../images/NPC/zeus/Principe Zeus.jpeg",
        nome: "Celestrion ",
        titulo: "Principe de Zeus",
        ascendencia: "Zeus",
        linhagem: "Maximus",
        dominio: "Raio e Vento",
        elemento: "Tempestade",
        classe: "Espadachim",
        oficio: "Militar",
        personalidade: "Paquerador, Orgulhoso, Companheiro",
    },   
    {
        imagem: "../images/NPC/zeus/Segundo Zeus.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Zeus",
        ascendencia: "Zeus",
        linhagem: "Raicrow",
        dominio: "Raio e Transformação",
        elemento: "Raio",
        classe: "Mago",
        oficio: "Arcanista",
        personalidade: "Corajoso, Esportista, Amável",
    },   
    {
        imagem: "../images/NPC/zeus/Principe Hebe.jpeg",
        nome: "nome ",
        titulo: "Principe de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/zeus/Segundo Hebe.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Terceiro Hebe.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Principe Boreas.jpeg",
        nome: "nome ",
        titulo: "Principe de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/zeus/Segundo Boreas.jpeg",
        nome: "nome ",
        titulo: "Segundo de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Terceiro Boreas.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/zeus/Principe hercules.jpeg",
        nome: "nome ",
        titulo: "Principe de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/zeus/Segundo hercules.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Terceiro hercules.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
];

export const hades = [
    {
        imagem: "../images/NPC/hades/Principe Hades.jpeg",
        nome: "Terminus",
        titulo: "Principe de Hades",
        ascendencia: "Hades",
        linhagem: "Inferni",
        dominio: "Subterrâneo e Trevas",
        elemento: "Terra",
        classe: "Feiticeiro",
        oficio: "Domador",
        personalidade: "Depressivo, Emo, Antisocial",
    },  
    {
        imagem: "../images/NPC/hades/Segundo Hades.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hades",
        ascendencia: "Hades",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
    {
        imagem: "../images/NPC/hades/Princesa Hécate.jpeg",
        nome: "Corvina",
        titulo: "Princesa de Hecate",
        ascendencia: "Hecate",
        linhagem: "Babayaga",
        dominio: "Magia",
        elemento: "Trevas",
        classe: "Bruxa",
        oficio: "Arcanista",
        personalidade: "Diligente, Séria, Antipática",
    },  
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hecate",
        ascendencia: "Hecate",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hades/Principe Thanatos.jpeg",
        nome: "Zero",
        titulo: "Principe de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "Corvus",
        dominio: "Morte e Fauna",
        elemento: "Gelo",
        classe: "Druida",
        oficio: "Domador",
        personalidade: "Dedicado, Teimoso, Crente",
    },  
    {
        imagem: "../images/NPC/hades/Segundo Thanatos.jpeg",
        nome: "nome ",
        titulo: "Segundo de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hades/Terceiro Thanatos.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/hades/Principe Hipnos.jpeg",
        nome: "nome ",
        titulo: "Principe de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hades/Segundo Hipnos.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hades/Terceiro Hipnos.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
];

export const posseidon = [
    {
        imagem: "../images/NPC/Posseidon/Principe Posseidon.jpeg",
        nome: "nome",
        titulo: "Principe de Posseidon",
        ascendencia: "Posseidon",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/Posseidon/Segundo Posseidon.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Posseidon",
        ascendencia: "Posseidon",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/Posseidon/Principe Tritão.jpeg",
        nome: "nome ",
        titulo: "Principe de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/Posseidon/Segundo Tritão.jpeg",
        nome: "nome ",
        titulo: "Segundo de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/Posseidon/Terceiro Tritão.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/Posseidon/Princesa Nereu.jpeg",
        nome: "nome ",
        titulo: "Principe de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/Posseidon/Segundo Nereu.jpeg",
        nome: "nome ",
        titulo: "Segundo de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/Posseidon/Terceiro Nereu.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/Posseidon/Princesa Aqueloo.jpeg",
        nome: "nome ",
        titulo: "Principe de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/Posseidon/Segundo Aqueloo.jpeg",
        nome: "nome ",
        titulo: "Segundo de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/Posseidon/Terceiro Aqueloo.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
];

export const hera = [  
    {
        imagem: "../images/NPC/hera/Segunda Hera.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Hera",
        ascendencia: "Hera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Iris.jpeg",
        nome: "nome ",
        titulo: "Principe de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Iris.jpeg",
        nome: "nome ",
        titulo: "Segundo de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Terceira Iris.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Héspera.jpeg",
        nome: "nome ",
        titulo: "Principe de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Héspera.jpeg",
        nome: "nome ",
        titulo: "Segundo de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Terceira Héspera.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/hera/Princesa Argos.jpeg",
        nome: "nome ",
        titulo: "Principe de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Argos.jpeg",
        nome: "nome ",
        titulo: "Segundo de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Terceiro Argos.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
];