export const personalidades = [
    "Inabalável", "Trapaceiro", "Introvertido", "Carismático", "Servo", "Indeciso", "Procrastinador", "Imparcial", 
    "Modesto", "Corajoso", "Valente", "Tímido", "Gentil", "Atencioso", "Irritadiço", "Patriota", "Indiferente", 
    "Sonolento", "Apostador", "Esportista", "Sociopata", "Estranho", "Espalhafatoso", "Idol", "Simplista", "Sério", 
    "Diligente", "Calmo", "Justiça", "Franqueza", "Amizade", "Companheirismo", "Questionador", "Criativo", 
    "Protetor", "Atrapalhado", "Aproveitador", "Fofoqueiro", "Anti-social", "Apaixonado", "Calado", "Traíra", 
    "Narcisista", "Competidor", "Pacifista", "Compreensivo", "Gosto caro", "Briguento", "Preguiçoso", "Força da natureza", 
    "Precipitado", "Inocente", "Altruísta", "Herói", "Alegre", "Humilde", "Castrado", "Honesto", "Dedicado", "Derrotista", 
    "Falador", "Paquerador", "Palhaço", "Provocador", "Líder", "Amável", "Honrado", "Precavido", "Audacioso", "Respeitoso", 
    "Teimoso", "Distraído", "Inquieto", "Antipático", "Crente", "Mentiroso", "Invejoso", "Ganancioso", "Orgulhoso", 
    "Malicioso", "Fervoroso", "Guloso", "Ingrato", "Hipócrita", "Exibicionista", "Exigente", "Estudioso", "Hospitaleiro", 
    "Mal educado", "Paladar exótico", "Companheiro", "Complexo de inferioridade", "Infantil", "Amante da natureza", 
    "Inseguro", "poucas palavras"
];

export const apoio = [
    {
        imagem: "../images/NPC/Cristal.jpeg",
        nome: "Cristal",
        titulo: "Madame Cristal",
        ascendencia: "Delfos",
        linhagem: "Krystallo",
        dominio: "Oráculo",
        elemento: "Cristal",
        classe: "Mago Artífice Lv 16",
        oficio: "Vedendor Lv 10",
        personalidade: "Imparcial, Trapaceira, Curiosa",
    },  
    {
        imagem: "../images/NPC/Ludy.jpeg",
        nome: "Ludy",
        titulo: "Cartógrafo Explorador",
        ascendencia: "Hebe",
        linhagem: "---",
        dominio: "Juventude",
        elemento: "Tinta",
        classe: "Mago, Bruxo Lv 16",
        oficio: "Vedendor Lv 10",
        personalidade: "Mentiroso, Trapaceiro, Oportunista",
    },  
    {
        imagem: "../images/NPC/Mordomo Hades.jpeg",
        nome: "Koraki",
        titulo: "Mordomo da Casa de Hades",
        ascendencia: "Hécate",
        linhagem: "Inferni",
        dominio: "Magia",
        elemento: "Espaço",
        classe: "Mago Especialista Lv 16",
        oficio: "Mordomo Lv 10",
        personalidade: "Servo, Diligente, Poucas Palavras",
    },    
    {
        imagem: "../images/NPC/Lucio.jpeg",
        nome: "Lucio",
        titulo: "Carroceiro das Corujas",
        ascendencia: "Maia e Athena",
        linhagem: "Diarríktis",
        dominio: "Ladão",
        elemento: "Vento",
        classe: "Ladino Lv 2",
        oficio: "Faz Tudo Lv 7",
        personalidade: "Mentiroso, Folgado, Criativo",
    },  
    {
        imagem: "../images/NPC/Domia.jpeg",
        nome: "Domia",
        titulo: "Guardiã do Bosque",
        ascendencia: "Aracne",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Fios",
        classe: "Mago Lv 5",
        oficio: "Arcanista Lv10",
        personalidade: "Diligente, Gentil, Esforçada",
    }, 
    {
        imagem: "../images/NPC/Scarlat.jpeg",
        nome: "Scarlat",
        titulo: "Joia de Fogo",
        ascendencia: "Héstia",
        linhagem: "Apoloni",
        dominio: "Fogo",
        elemento: "Rubi",
        classe: "Feiticeiro Lv 2",
        oficio: "Arcanista Lv 5",
        personalidade: "Estudiosa, Leal, Amável",
    }, 
    {
        imagem: "../images/NPC/Marine.jpeg",
        nome: "Marine",
        titulo: "Joia de Água",
        ascendencia: "Nereu e Hécate",
        linhagem: "Atlanti",
        dominio: "Água",
        elemento: "Aquamarine",
        classe: "Feiticeiro Lv 2",
        oficio: "Arcanista Lv 5",
        personalidade: "Questionadora, Intrivertida e Calada",
    }, 
    {
        imagem: "../images/NPC/Magnus.jpeg",
        nome: "Magnus",
        titulo: "Porteiro da Biblioteca",
        ascendencia: "Hécate",
        linhagem: "---",
        dominio: "Magia",
        elemento: "Água, Vento",
        classe: "Mago Lv 2",
        oficio: "Arcanista Lv 10",
        personalidade: "Preguisoço, Dedicado, Traira",
    }, 
    {
        imagem: "../images/NPC/Limenor.jpeg",
        nome: "Limenor",
        titulo: "Segurança da Princesa Monstro",
        ascendencia: "Nike",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Terra, Fogo",
        classe: "Espadachim Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Diligente, Forla da Natureza, Inabalável",
    }, 
    {
        imagem: "../images/NPC/Tarvim.jpeg",
        nome: "Tarvim",
        titulo: "Agraciado de Hera",
        ascendencia: "Artémis, Hera",
        linhagem: "---",
        dominio: "Caça",
        elemento: "Terra Água",
        classe: "Espadachim Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Força da natureza, Companheiro, Corajoso",
    }, 
    {
        imagem: "../images/NPC/Teseu.jpeg",
        nome: "Teseu",
        titulo: "Ninfa Macho",
        ascendencia: "Ígena",
        linhagem: "---",
        dominio: "Ninfa do Fogo",
        elemento: "Plasma",
        classe: "Feiticeiro Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Companheiro, Aproveitador, Criativo",
    }, 
    {
        imagem: "../images/NPC/Thales.jpeg",
        nome: "Thales",
        titulo: "Canção do Mar",
        ascendencia: "Pã",
        linhagem: "Apoloni",
        dominio: "Música",
        elemento: "Som",
        classe: "Bardo Lv 2",
        oficio: "Artista Lv 5",
        personalidade: "Servo, Patriota, Sonolento",
    }, 
    {
        imagem: "../images/NPC/Briael.jpeg",
        nome: "Briael",
        titulo: "Profeta das Harpias",
        ascendencia: "Ícaro e Delfos",
        linhagem: "Apoloni",
        dominio: "Harpias",
        elemento: "Pressão",
        classe: "Lanceiro Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Simplista, Corajoso, Companheiro",
    }, 
    {
        imagem: "../images/NPC/herfesto/Segunda Herfesto.jpeg",
        nome: "Amélia",
        titulo: "Segunda Herfesto",
        ascendencia: "Herfesto",
        linhagem: "Vulcan",
        dominio: "Tecnologia e Metal",
        elemento: "Metal",
        classe: "Mago Lv 0",
        oficio: "Engenheira Lv 5",
        personalidade: "Diligente, Criativa, Aproveitadora",
    },  
    {
        imagem: "../images/NPC/afrodite/Terceiro Eros.jpeg",
        nome: "Carina",
        titulo: "Terceira Eros",
        ascendencia: "Eros",
        linhagem: "Rose",
        dominio: "Amor e Carisma",
        elemento: "Som",
        classe: "Bardo Lv 0",
        oficio: "Artista Lv 5",
        personalidade: "Compreensiva, Sociopata, Palahaça",
    }, 
    {
        imagem: "../images/NPC/afrodite/Terceiro Thalia.jpeg",
        nome: "Mirana",
        titulo: "Terceira Thalia",
        ascendencia: "Thalia",
        linhagem: "Rose",
        dominio: "Flores e Carisma",
        elemento: "Flores",
        classe: "Druida Lv 0",
        oficio: "Botânica Lv 5",
        personalidade: "Estudiosa, Imparcial, Compreensiva",
    }, 
    {
        imagem: "../images/NPC/Rim.jpeg",
        nome: "Rim",
        titulo: "Ninfa Tritão",
        ascendencia: "---",
        linhagem: "---",
        dominio: "---",
        elemento: "Água",
        classe: "Feiticeira Lv 10",
        oficio: "Modelo Lv 10",
        personalidade: "Provocadora, Lider, Simplista",
    }, 
    {
        imagem: "../images/NPC/Aqua.jpeg",
        nome: "Aqua",
        titulo: "A mais bela do lago",
        ascendencia: "---",
        linhagem: "---",
        dominio: "---",
        elemento: "Água",
        classe: "Feiticeira Lv 10",
        oficio: "Modelo Lv 10",
        personalidade: "Paqueradora, Sonhadora, Gentil",
    }, 
];

export const zeus = [
    {
        imagem: "../images/NPC/zeus/Segundo Zeus.jpeg",
        nome: "Electraeus ",
        titulo: "Principe de Zeus",
        ascendencia: "Zeus",
        linhagem: "Raicrow",
        dominio: "Raio e Transformação",
        elemento: "Raio",
        classe: "Mago",
        oficio: "Arcanista",
        personalidade: "Corajoso, Esportista, Amável",
    },   
    {
        imagem: "../images/NPC/zeus/Principe Zeus.jpeg",
        nome: "Celestrion ",
        titulo: "Segundo de Zeus",
        ascendencia: "Zeus",
        linhagem: "Maximus",
        dominio: "Raio e Vento",
        elemento: "Tempestade",
        classe: "Espadachim",
        oficio: "Militar",
        personalidade: "Paquerador, Orgulhoso, Companheiro",
    },   
    {
        imagem: "../images/NPC/zeus/Principe Hebe.jpeg",
        nome: "nome ",
        titulo: "Principe de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/zeus/Segundo Hebe.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Terceiro Hebe.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hebe",
        ascendencia: "Hebe",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Principe Boreas.jpeg",
        nome: "nome ",
        titulo: "Principe de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/zeus/Segundo Boreas.jpeg",
        nome: "nome ",
        titulo: "Segundo de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Terceiro Boreas.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Bóreas",
        ascendencia: "Bóreas",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/zeus/Principe Hercules.jpeg",
        nome: "nome ",
        titulo: "Principe de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/zeus/Segundo Hercules.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/zeus/Terceiro Hercules.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hércules",
        ascendencia: "Hércules",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
];

export const hades = [
    {
        imagem: "../images/NPC/hades/Principe Hades.jpeg",
        nome: "Terminus",
        titulo: "Principe de Hades",
        ascendencia: "Hades",
        linhagem: "Inferni",
        dominio: "Subterrâneo e Trevas",
        elemento: "Terra",
        classe: "Feiticeiro",
        oficio: "Domador",
        personalidade: "Depressivo, Emo, Antisocial",
    },  
    {
        imagem: "../images/NPC/hades/Segundo Hades.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hades",
        ascendencia: "Hades",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
    {
        imagem: "../images/NPC/hades/Princesa Hécate.jpeg",
        nome: "Corvina",
        titulo: "Princesa de Hecate",
        ascendencia: "Hecate",
        linhagem: "Babayaga",
        dominio: "Magia",
        elemento: "Trevas",
        classe: "Bruxa",
        oficio: "Arcanista",
        personalidade: "Diligente, Séria, Antipática",
    },  
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hecate",
        ascendencia: "Hecate",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hades/Principe Thanatos.jpeg",
        nome: "Zero",
        titulo: "Principe de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "Corvus",
        dominio: "Morte e Fauna",
        elemento: "Gelo",
        classe: "Druida",
        oficio: "Domador",
        personalidade: "Dedicado, Teimoso, Crente",
    },  
    {
        imagem: "../images/NPC/hades/Segundo Thanatos.jpeg",
        nome: "nome ",
        titulo: "Segundo de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hades/Terceiro Thanatos.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Thanatos",
        ascendencia: "Thanatos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/hades/Principe Hipnos.jpeg",
        nome: "nome ",
        titulo: "Principe de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hades/Segundo Hipnos.jpeg",
        nome: "nome ",
        titulo: "Segundo de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hades/Terceiro Hipnos.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Hipnos",
        ascendencia: "Hipnos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
];

export const posseidon = [
    {
        imagem: "../images/NPC/posseidon/Principe Posseidon.jpeg",
        nome: "nome",
        titulo: "Principe de Posseidon",
        ascendencia: "Posseidon",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/posseidon/Segundo Posseidon.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Posseidon",
        ascendencia: "Posseidon",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/posseidon/Principe Tritao.jpeg",
        nome: "nome ",
        titulo: "Principe de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/posseidon/Segundo Tritao.jpeg",
        nome: "nome ",
        titulo: "Segundo de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/posseidon/Terceiro Tritao.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Tritão",
        ascendencia: "Tritão",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/posseidon/Princesa Nereu.jpeg",
        nome: "nome ",
        titulo: "Principe de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/posseidon/Segundo Nereu.jpeg",
        nome: "nome ",
        titulo: "Segundo de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/posseidon/Terceiro Nereu.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Nereu",
        ascendencia: "Nereu",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/posseidon/Princesa Aqueloo.jpeg",
        nome: "nome ",
        titulo: "Principe de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/posseidon/Segundo Aqueloo.jpeg",
        nome: "nome ",
        titulo: "Segundo de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/posseidon/Terceiro Aqueloo.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
];

export const hera = [  
    {
        imagem: "../images/NPC/hera/Segunda Hera.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Hera",
        ascendencia: "Hera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Iris.jpeg",
        nome: "nome ",
        titulo: "Principe de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Iris.jpeg",
        nome: "nome ",
        titulo: "Segundo de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Terceira Iris.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Iris",
        ascendencia: "Iris",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Héspera.jpeg",
        nome: "nome ",
        titulo: "Principe de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Héspera.jpeg",
        nome: "nome ",
        titulo: "Segundo de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Terceira Héspera.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Héspera",
        ascendencia: "Héspera",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },    
    {
        imagem: "../images/NPC/hera/Princesa Argos.jpeg",
        nome: "nome ",
        titulo: "Principe de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Argos.jpeg",
        nome: "nome ",
        titulo: "Segundo de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/NPC/hera/Terceiro Argos.jpeg",
        nome: "nome ",
        titulo: "Terceiro de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },   
    {
        imagem: "../images/ausente.jpg",
        nome: "nome ",
        titulo: "Plebeu de Argos",
        ascendencia: "Argos",
        linhagem: "nenhum",
        dominio: "nenhum",
        elemento: "nenhum",
        classe: "nenhum",
        oficio: "nenhum",
        personalidade: "nenhum",
    },     
];