export const athena = [
    {
        imagem: "../images/NPC/athena/Principe Athena.jpeg",
        nome: "Palas",
        titulo: "Princesa de Athena",
        ascendencia: "Athena",
        linhagem: "---",
        dominio: "Inteligência e Vento",
        elemento: "Raio",
        classe: "Mago Lv0",
        oficio: "Arcanista Lv 10",
        personalidade: "Disciplinada, Metodica, Calculista",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Athena.jpeg",
        nome: "Jonas",
        titulo: "Segundo de Athena",
        ascendencia: "Athena",
        linhagem: "---",
        dominio: "Terra e Estratégia",
        elemento: "Sismico",
        classe: "Lutador Lv1",
        oficio: "Militar Lv 10",
        personalidade: "Malicioso, Oportunista, Crente",
    },   
    {
        imagem: "../images/NPC/athena/Naguine.jpeg",
        nome: "Naguine",
        titulo: "Princesa Monstro",
        ascendencia: "Medusa",
        linhagem: "---",
        dominio: "Gorgona",
        elemento: "Veneno",
        classe: "Druida Lv1",
        oficio: "Arcanbista Lv 5",
        personalidade: "---, ---, ---",
    },    
    {
        imagem: "../images/NPC/athena/Principe Nike.jpeg",
        nome: "Vitoria",
        titulo: "Princesa de Nike",
        ascendencia: "Nike",
        linhagem: "---",
        dominio: "Vitória e Destreza",
        elemento: "Raio",
        classe: "Lanceiro Lv1",
        oficio: "Militar Lv 10",
        personalidade: "Esportista, Leal, Séria",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Nike.jpeg",
        nome: "Dafne",
        titulo: "Segunda de Nike",
        ascendencia: "Nike",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Metal",
        classe: "Espadachim Lv1",
        oficio: "Militar Lv 10",
        personalidade: "Diligente, Precavida, Serva",
    },   
    {
        imagem: "../images/NPC/athena/Terceiro Nike.jpeg",
        nome: "Medeia",
        titulo: "Terceira de Nike",
        ascendencia: "Nike",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Trevas",
        classe: "Ladino Lv1",
        oficio: "Bandido Lv 10",
        personalidade: "Carismática, Inquieta, Maliciosa",
    },  
    {
        imagem: "../images/NPC/athena/Principe Medusa.jpeg",
        nome: "Caroline",
        titulo: "Princesa de Medusa",
        ascendencia: "Medusa",
        linhagem: "---",
        dominio: "Gorgona e Veneno",
        elemento: "Trevas",
        classe: "Lutador lv0",
        oficio: "Arcanista Lv 10",
        personalidade: "Ninfomaníaca, Gananciosa, Audaciosa",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Medusa.jpeg",
        nome: "Areteia",
        titulo: "Segunda de Medusa",
        ascendencia: "Medusa",
        linhagem: "---",
        dominio: "Gorgona",
        elemento: "Veneno e Fogo",
        classe: "Ladino lv0",
        oficio: "Bandido Lv 10",
        personalidade: "Calada, Patriota, Companheira",
    },   
    {
        imagem: "../images/NPC/athena/Terceiro Medusa.jpeg",
        nome: "Lísistrata",
        titulo: "Terceira de Medusa",
        ascendencia: "Medusa",
        linhagem: "---",
        dominio: "Gorgona",
        elemento: "Trevas e Veneno",
        classe: "Feiticeiro Lv0",
        oficio: "Coveira Lv 10",
        personalidade: "Diligente, Cruel, Imparcial",
    },  
    {
        imagem: "../images/NPC/athena/Principe Aracne.jpeg",
        nome: "Tarântula",
        titulo: "Princesa de Aracne",
        ascendencia: "Aracne",
        linhagem: "---",
        dominio: "Aracne e Oráculo",
        elemento: "Fios e Veneno",
        classe: "Mago lv1",
        oficio: "Sacerdote Lv 10",
        personalidade: "Dedicada, Gentil, Diligente",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Aracne.jpeg",
        nome: "Sophia",
        titulo: "Segunda de Aracne",
        ascendencia: "Aracne",
        linhagem: "---",
        dominio: "Aracne",
        elemento: "Fios e Veneno",
        classe: "Mago Lv0",
        oficio: "Bibliotecaria Lv 10",
        personalidade: "Estudiosa, Diligente, Atenciosa",
    },   
    {
        imagem: "../images/NPC/Domia.jpeg",
        nome: "Domia",
        titulo: "Guardiã do Bosque",
        ascendencia: "Aracne",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Fios",
        classe: "Mago Lv 8",
        oficio: "Arcanista Lv10",
        personalidade: "Diligente, Gentil, Esforçada",
    }, 
];
