export const athena = [
    {
        imagem: "../images/NPC/athena/Principe Athena.jpeg",
        nome: "Celestrion",
        titulo: "Principe de Athena",
        ascendencia: "Athena",
        linhagem: "Windwhisper",
        dominio: "Tempestade",
        elemento: "Raio",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Paquerador, Orgulhoso, Companheiro",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Athena.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Athena",
        ascendencia: "Athena",
        linhagem: "Perseu",
        dominio: "Raio e Transformação",
        elemento: "Vento e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 7",
        personalidade: "Corajoso, Esportista, Amável",
    },   
    {
        imagem: "../images/NPC/athena/Naguine.jpeg",
        nome: "Naguine",
        titulo: "Princesa Monstro",
        ascendencia: "Medusa",
        linhagem: "Windwhisper",
        dominio: "Oxigênio",
        elemento: "Água",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 7",
        personalidade: "Companheiro, Leal, Servo",
    },    
    {
        imagem: "../images/NPC/athena/Principe Nike.jpeg",
        nome: "Aiolos",
        titulo: "Principe de Nike",
        ascendencia: "Nike",
        linhagem: "Perseu",
        dominio: "Juventude e Fogo",
        elemento: "Flama",
        classe: "Espadachim",
        oficio: "Militar Lv 9",
        personalidade: "Franqueza, Leal, Falador",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Nike.jpeg",
        nome: "Adonis",
        titulo: "Segundo de Nike",
        ascendencia: "Nike",
        linhagem: "Maximus",
        dominio: "Fogo",
        elemento: "Vento e Terra",
        classe: "Lutador",
        oficio: "Militar Lv 5",
        personalidade: "Servo, Malicioso, Cruel",
    },   
    {
        imagem: "../images/NPC/athena/Terceiro Nike.jpeg",
        nome: "Heberia",
        titulo: "Terceiro de Nike",
        ascendencia: "Nike",
        linhagem: "Maximus",
        dominio: "Fartura",
        elemento: "Água e Terra",
        classe: "Bardo",
        oficio: "Copeira Lv 10",
        personalidade: "Diligente, Compreensiva, Gentil",
    },  
    {
        imagem: "../images/NPC/athena/Principe Medusa.jpeg",
        nome: "Zopyros",
        titulo: "Principe de Medusa",
        ascendencia: "Medusa",
        linhagem: "Perseus",
        dominio: "Vento e Ninfa do Vento",
        elemento: "Tempestade",
        classe: "Feiticeiro",
        oficio: "Arcanista Lv 9",
        personalidade: "Herói, Altruista, Atrapalhado",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Medusa.jpeg",
        nome: "Menelaos",
        titulo: "Segundo de Medusa",
        ascendencia: "Medusa",
        linhagem: "Windwhisper",
        dominio: "Vento",
        elemento: "Água e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 10",
        personalidade: "Ingrato, Sério, Anti-social",
    },   
    {
        imagem: "../images/NPC/athena/Terceiro Medusa.jpeg",
        nome: "Jason",
        titulo: "Terceiro de Medusa",
        ascendencia: "Medusa",
        linhagem: "Windwhisper",
        dominio: "Oxigênio",
        elemento: "Água",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 7",
        personalidade: "Companheiro, Leal, Servo",
    },  
    {
        imagem: "../images/NPC/athena/Principe Aracne.jpeg",
        nome: "Cadmus",
        titulo: "Principe de Aracne",
        ascendencia: "Aracne",
        linhagem: "Maximus",
        dominio: "Força e Resistência",
        elemento: "Metal",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Sério, Orgulhoso, Ignorante",
    },  
    {
        imagem: "../images/NPC/athena/Segundo Aracne.jpeg",
        nome: "Charon",
        titulo: "Segundo de Aracne",
        ascendencia: "Aracne",
        linhagem: "Maximus",
        dominio: "Destreza",
        elemento: "Metal",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 10",
        personalidade: "Antipático, Orgulhoso, Protetor",
    },   
    {
        imagem: "../images/NPC/athena/Terceiro Aracne.jpeg",
        nome: "Atalanta",
        titulo: "Terceiro de Aracne",
        ascendencia: "Aracne",
        linhagem: "Maximus",
        dominio: "Carisma",
        elemento: "Som",
        classe: "Bardo",
        oficio: "Dançarina Lv 10",
        personalidade: "Narcisista, Franqueza, Gulosa",
    },   
];
