export const demeter = [
    {
        imagem: "../images/NPC/demeter/Principe Demeter.jpeg",
        nome: "Demeterio",
        titulo: "Principe de Demeter",
        ascendencia: "Demeter",
        linhagem: "Windwhisper",
        dominio: "Tempestade",
        elemento: "Raio",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Paquerador, Orgulhoso, Companheiro",
    },  
    {
        imagem: "../images/NPC/demeter/Segundo Demeter.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Demeter",
        ascendencia: "Demeter",
        linhagem: "Perseu",
        dominio: "Raio e Transformação",
        elemento: "Vento e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 7",
        personalidade: "Corajoso, Esportista, Amável",
    },    
    {
        imagem: "../images/NPC/demeter/Principe Tritolemo.jpeg",
        nome: "Aiolos",
        titulo: "Principe de Tritolemo",
        ascendencia: "Tritolemo",
        linhagem: "Perseu",
        dominio: "Juventude e Fogo",
        elemento: "Flama",
        classe: "Espadachim",
        oficio: "Militar Lv 9",
        personalidade: "Franqueza, Leal, Falador",
    },  
    {
        imagem: "../images/NPC/demeter/Segundo Tritolemo.jpeg",
        nome: "Adonis",
        titulo: "Segundo de Tritolemo",
        ascendencia: "Tritolemo",
        linhagem: "Maximus",
        dominio: "Fogo",
        elemento: "Vento e Terra",
        classe: "Lutador",
        oficio: "Militar Lv 5",
        personalidade: "Servo, Malicioso, Cruel",
    },   
    {
        imagem: "../images/NPC/demeter/Terceiro Tritolemo.jpeg",
        nome: "Heberia",
        titulo: "Terceiro de Tritolemo",
        ascendencia: "Tritolemo",
        linhagem: "Maximus",
        dominio: "Fartura",
        elemento: "Água e Terra",
        classe: "Bardo",
        oficio: "Copeira Lv 10",
        personalidade: "Diligente, Compreensiva, Gentil",
    },   
    {
        imagem: "../images/NPC/demeter/Principe Horas.jpeg",
        nome: "Zopyros",
        titulo: "Principe de Horas",
        ascendencia: "Horas",
        linhagem: "Perseus",
        dominio: "Vento e Ninfa do Vento",
        elemento: "Tempestade",
        classe: "Feiticeiro",
        oficio: "Arcanista Lv 9",
        personalidade: "Herói, Altruista, Atrapalhado",
    },  
    {
        imagem: "../images/NPC/demeter/Segundo Horas.jpeg",
        nome: "Menelaos",
        titulo: "Segundo de Horas",
        ascendencia: "Horas",
        linhagem: "Windwhisper",
        dominio: "Vento",
        elemento: "Água e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 10",
        personalidade: "Ingrato, Sério, Anti-social",
    },   
    {
        imagem: "../images/NPC/demeter/Terceiro Horas.jpeg",
        nome: "Jason",
        titulo: "Terceiro de Horas",
        ascendencia: "Horas",
        linhagem: "Windwhisper",
        dominio: "Oxigênio",
        elemento: "Água",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 7",
        personalidade: "Companheiro, Leal, Servo",
    },   
    {
        imagem: "../images/NPC/demeter/Principe Driade.jpeg",
        nome: "Cadmus",
        titulo: "Principe de Driade",
        ascendencia: "Driade",
        linhagem: "Maximus",
        dominio: "Força e Resistência",
        elemento: "Metal",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Sério, Orgulhoso, Ignorante",
    },  
    {
        imagem: "../images/NPC/demeter/Segundo Driade.jpeg",
        nome: "Charon",
        titulo: "Segundo de Driade",
        ascendencia: "Driade",
        linhagem: "Maximus",
        dominio: "Destreza",
        elemento: "Metal",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 10",
        personalidade: "Antipático, Orgulhoso, Protetor",
    },   
    {
        imagem: "../images/NPC/demeter/Terceiro Driade.jpeg",
        nome: "Atalanta",
        titulo: "Terceiro de Driade",
        ascendencia: "Driade",
        linhagem: "Maximus",
        dominio: "Carisma",
        elemento: "Som",
        classe: "Bardo",
        oficio: "Dançarina Lv 10",
        personalidade: "Narcisista, Franqueza, Gulosa",
    },   
];
