export const dionisio = [
    {
        imagem: "../images/NPC/dionisio/Principe Dionisio.jpeg",
        nome: "Celestrion",
        titulo: "Principe de Dionisio",
        ascendencia: "Dionisio",
        linhagem: "Windwhisper",
        dominio: "Tempestade",
        elemento: "Raio",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Paquerador, Orgulhoso, Companheiro",
    },   
    {
        imagem: "../images/NPC/dionisio/Segundo Dionisio.jpeg",
        nome: "Electraeus ",
        titulo: "Segundo de Dionisio",
        ascendencia: "Dionisio",
        linhagem: "Perseu",
        dominio: "Raio e Transformação",
        elemento: "Vento e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 7",
        personalidade: "Corajoso, Esportista, Amável",
    },   
    {
        imagem: "../images/NPC/dionisio/Principe Menade.jpeg",
        nome: "Aiolos",
        titulo: "Principe de Menade",
        ascendencia: "Menade",
        linhagem: "Perseu",
        dominio: "Juventude e Fogo",
        elemento: "Flama",
        classe: "Espadachim",
        oficio: "Militar Lv 9",
        personalidade: "Franqueza, Leal, Falador",
    },  
    {
        imagem: "../images/NPC/dionisio/Segundo Menade.jpeg",
        nome: "Adonis",
        titulo: "Segundo de Menade",
        ascendencia: "Menade",
        linhagem: "Maximus",
        dominio: "Fogo",
        elemento: "Vento e Terra",
        classe: "Lutador",
        oficio: "Militar Lv 5",
        personalidade: "Servo, Malicioso, Cruel",
    },   
    {
        imagem: "../images/NPC/dionisio/Terceiro Menade.jpeg",
        nome: "Heberia",
        titulo: "Terceiro de Menade",
        ascendencia: "Menade",
        linhagem: "Maximus",
        dominio: "Fartura",
        elemento: "Água e Terra",
        classe: "Bardo",
        oficio: "Copeira Lv 10",
        personalidade: "Diligente, Compreensiva, Gentil",
    },   
    {
        imagem: "../images/NPC/dionisio/Principe Silenos.jpeg",
        nome: "Zopyros",
        titulo: "Principe de Silenos",
        ascendencia: "Silenos",
        linhagem: "Perseus",
        dominio: "Vento e Ninfa do Vento",
        elemento: "Tempestade",
        classe: "Feiticeiro",
        oficio: "Arcanista Lv 9",
        personalidade: "Herói, Altruista, Atrapalhado",
    },  
    {
        imagem: "../images/NPC/dionisio/Segundo Silenos.jpeg",
        nome: "Menelaos",
        titulo: "Segundo de Silenos",
        ascendencia: "Silenos",
        linhagem: "Windwhisper",
        dominio: "Vento",
        elemento: "Água e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 10",
        personalidade: "Ingrato, Sério, Anti-social",
    },   
    {
        imagem: "../images/NPC/dionisio/Terceiro Silenos.jpeg",
        nome: "Jason",
        titulo: "Terceiro de Silenos",
        ascendencia: "Silenos",
        linhagem: "Windwhisper",
        dominio: "Oxigênio",
        elemento: "Água",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 7",
        personalidade: "Companheiro, Leal, Servo",
    },   
    {
        imagem: "../images/NPC/dionisio/Principe Icaro.jpeg",
        nome: "Cadmus",
        titulo: "Principe de Icaro",
        ascendencia: "Icaro",
        linhagem: "Maximus",
        dominio: "Força e Resistência",
        elemento: "Metal",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Sério, Orgulhoso, Ignorante",
    },  
    {
        imagem: "../images/NPC/dionisio/Segundo Icaro.jpeg",
        nome: "Charon",
        titulo: "Segundo de Icaro",
        ascendencia: "Icaro",
        linhagem: "Maximus",
        dominio: "Destreza",
        elemento: "Metal",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 10",
        personalidade: "Antipático, Orgulhoso, Protetor",
    },   
    {
        imagem: "../images/NPC/dionisio/Terceiro Icaro.jpeg",
        nome: "Atalanta",
        titulo: "Terceiro de Icaro",
        ascendencia: "Icaro",
        linhagem: "Maximus",
        dominio: "Carisma",
        elemento: "Som",
        classe: "Bardo",
        oficio: "Dançarina Lv 10",
        personalidade: "Narcisista, Franqueza, Gulosa",
    },   
];
