export const apoio = [
    {
        imagem: "../images/NPC/Cristal.jpeg",
        nome: "Cristal",
        titulo: "Madame Cristal",
        ascendencia: "Delfos",
        linhagem: "Krystallo",
        dominio: "Oráculo",
        elemento: "Cristal",
        classe: "Mago Artífice Lv 16",
        oficio: "Vedendor Lv 10",
        personalidade: "Imparcial, Trapaceira, Curiosa",
    },  
    {
        imagem: "../images/NPC/Ludy.jpeg",
        nome: "Ludy",
        titulo: "Cartógrafo Explorador",
        ascendencia: "Hebe",
        linhagem: "---",
        dominio: "Juventude",
        elemento: "Tinta",
        classe: "Mago, Bruxo Lv 16",
        oficio: "Vedendor Lv 10",
        personalidade: "Mentiroso, Trapaceiro, Oportunista",
    },  
    {
        imagem: "../images/NPC/Mordomo Hades.jpeg",
        nome: "Koraki",
        titulo: "Mordomo da Casa de Hades",
        ascendencia: "Hécate",
        linhagem: "Inferni",
        dominio: "Magia",
        elemento: "Espaço",
        classe: "Mago Especialista Lv 16",
        oficio: "Mordomo Lv 10",
        personalidade: "Servo, Diligente, Poucas Palavras",
    },    
    {
        imagem: "../images/NPC/Lucio.jpeg",
        nome: "Lucio",
        titulo: "Carroceiro das Corujas",
        ascendencia: "Maia e Athena",
        linhagem: "Diarríktis",
        dominio: "Ladão",
        elemento: "Vento",
        classe: "Ladino Lv 2",
        oficio: "Faz Tudo Lv 7",
        personalidade: "Mentiroso, Folgado, Criativo",
    },  
    {
        imagem: "../images/NPC/Domia.jpeg",
        nome: "Domia",
        titulo: "Guardiã do Bosque",
        ascendencia: "Aracne",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Fios",
        classe: "Mago Lv 5",
        oficio: "Arcanista Lv10",
        personalidade: "Diligente, Gentil, Esforçada",
    }, 
    {
        imagem: "../images/NPC/Scarlat.jpeg",
        nome: "Scarlat",
        titulo: "Joia de Fogo",
        ascendencia: "Héstia",
        linhagem: "Apoloni",
        dominio: "Fogo",
        elemento: "Rubi",
        classe: "Feiticeiro Lv 2",
        oficio: "Arcanista Lv 5",
        personalidade: "Estudiosa, Leal, Amável",
    }, 
    {
        imagem: "../images/NPC/Marine.jpeg",
        nome: "Marine",
        titulo: "Joia de Água",
        ascendencia: "Nereu e Hécate",
        linhagem: "Atlanti",
        dominio: "Água",
        elemento: "Aquamarine",
        classe: "Feiticeiro Lv 2",
        oficio: "Arcanista Lv 5",
        personalidade: "Questionadora, Intrivertida e Calada",
    }, 
    {
        imagem: "../images/NPC/Magnus.jpeg",
        nome: "Magnus",
        titulo: "Porteiro da Biblioteca",
        ascendencia: "Hécate",
        linhagem: "---",
        dominio: "Magia",
        elemento: "Água, Vento",
        classe: "Mago Lv 2",
        oficio: "Arcanista Lv 10",
        personalidade: "Preguisoço, Dedicado, Traira",
    }, 
    {
        imagem: "../images/NPC/Limenor.jpeg",
        nome: "Limenor",
        titulo: "Segurança da Princesa Monstro",
        ascendencia: "Nike",
        linhagem: "---",
        dominio: "Vitoria",
        elemento: "Terra, Fogo",
        classe: "Espadachim Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Diligente, Forla da Natureza, Inabalável",
    }, 
    {
        imagem: "../images/NPC/Tarvim.jpeg",
        nome: "Tarvim",
        titulo: "Agraciado de Hera",
        ascendencia: "Artémis, Hera",
        linhagem: "---",
        dominio: "Caça",
        elemento: "Terra Água",
        classe: "Espadachim Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Força da natureza, Companheiro, Corajoso",
    }, 
    {
        imagem: "../images/NPC/Teseu.jpeg",
        nome: "Teseu",
        titulo: "Ninfa Macho",
        ascendencia: "Ígena",
        linhagem: "---",
        dominio: "Ninfa do Fogo",
        elemento: "Plasma",
        classe: "Feiticeiro Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Companheiro, Aproveitador, Criativo",
    }, 
    {
        imagem: "../images/NPC/Thales.jpeg",
        nome: "Thales",
        titulo: "Canção do Mar",
        ascendencia: "Pã",
        linhagem: "Apoloni",
        dominio: "Música",
        elemento: "Som",
        classe: "Bardo Lv 2",
        oficio: "Artista Lv 5",
        personalidade: "Servo, Patriota, Sonolento",
    }, 
    {
        imagem: "../images/NPC/Briael.jpeg",
        nome: "Briael",
        titulo: "Profeta das Harpias",
        ascendencia: "Ícaro e Delfos",
        linhagem: "Apoloni",
        dominio: "Harpias",
        elemento: "Pressão",
        classe: "Lanceiro Lv 2",
        oficio: "Militar Lv 5",
        personalidade: "Simplista, Corajoso, Companheiro",
    }, 
    {
        imagem: "../images/NPC/herfesto/Segunda Herfesto.jpeg",
        nome: "Amélia",
        titulo: "Segunda Herfesto",
        ascendencia: "Herfesto",
        linhagem: "Vulcan",
        dominio: "Tecnologia e Metal",
        elemento: "Metal",
        classe: "Mago Lv 0",
        oficio: "Engenheira Lv 5",
        personalidade: "Diligente, Criativa, Aproveitadora",
    },  
    {
        imagem: "../images/NPC/afrodite/Terceiro Eros.jpeg",
        nome: "Carina",
        titulo: "Terceira Eros",
        ascendencia: "Eros",
        linhagem: "Rose",
        dominio: "Amor e Carisma",
        elemento: "Som",
        classe: "Bardo Lv 0",
        oficio: "Artista Lv 5",
        personalidade: "Compreensiva, Sociopata, Palahaça",
    }, 
    {
        imagem: "../images/NPC/afrodite/Terceiro Thalia.jpeg",
        nome: "Mirana",
        titulo: "Terceira Thalia",
        ascendencia: "Thalia",
        linhagem: "Rose",
        dominio: "Flores e Carisma",
        elemento: "Flores",
        classe: "Druida Lv 0",
        oficio: "Botânica Lv 5",
        personalidade: "Estudiosa, Imparcial, Compreensiva",
    }, 
    {
        imagem: "../images/NPC/Rim.jpeg",
        nome: "Rim",
        titulo: "Ninfa Tritão",
        ascendencia: "---",
        linhagem: "---",
        dominio: "---",
        elemento: "Água",
        classe: "Feiticeira Lv 10",
        oficio: "Modelo Lv 10",
        personalidade: "Provocadora, Lider, Simplista",
    }, 
    {
        imagem: "../images/NPC/Aqua.jpeg",
        nome: "Aqua",
        titulo: "A mais bela do lago",
        ascendencia: "---",
        linhagem: "---",
        dominio: "---",
        elemento: "Água",
        classe: "Feiticeira Lv 10",
        oficio: "Modelo Lv 10",
        personalidade: "Paqueradora, Sonhadora, Gentil",
    }, 
    {
        imagem: "../images/NPC/Susako.jpeg",
        nome: "Susako",
        titulo: "Afinador Castelado do Nick",
        ascendencia: "Iris",
        linhagem: "Lumier",
        dominio: "Luz",
        elemento: "Cor Amarelo",
        classe: "Feiticeiro Lv 0",
        oficio: "Arcanista Lv 2",
        personalidade: "Inteligente, Modesto, Preguiçoso",
    },
];
