
export const hera = [  
    {
        imagem: "../images/NPC/hera/Segunda Hera.jpeg",
        nome: "Otrera",
        titulo: "Segunda Princesa",
        ascendencia: "Hera",
        linhagem: "Maximus",
        dominio: "Mulheres e Casamento",
        elemento: "Madeira",
        classe: "Bruxa",
        oficio: "Caçadora Lv 10",
        personalidade: "Apaixonada, Leal, Obediente",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Iris.jpeg",
        nome: "Melanipe",
        titulo: "Principe de Iris",
        ascendencia: "Iris",
        linhagem: "Lumier",
        dominio: "Cores e Mensagem",
        elemento: "Amarelo",
        classe: "Maga",
        oficio: "Sacerdotiza Lv 9",
        personalidade: "Amigável, Comunicativa, Gentil",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Iris.jpeg",
        nome: "Hipólita",
        titulo: "Segundo de Iris",
        ascendencia: "Iris",
        linhagem: "Lumier",
        dominio: "Cores e Ilusão",
        elemento: "Anil",
        classe: "Lanceira Lv 1",
        oficio: "Arcanista Lv 10",
        personalidade: "Séria, Intolerante, Metódica",
    },   
    {
        imagem: "../images/NPC/hera/Terceira Iris.jpeg",
        nome: "Pentesileia",
        titulo: "Terceiro de Iris",
        ascendencia: "Iris",
        linhagem: "Lumier",
        dominio: "Amarelo",
        elemento: "Chama Brilhante",
        classe: "Feiticeira",
        oficio: "Arcanista Lv 10",
        personalidade: "Orgulhosa, Honrada, Autoritária ",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Héspera.jpeg",
        nome: "Antíope",
        titulo: "Principe de Héspera",
        ascendencia: "Héspera",
        linhagem: "Amazona",
        dominio: "Ninfa da Primavera e Madeira",
        elemento: "Veneno",
        classe: "Feiticeira",
        oficio: "Botânica Lv 10",
        personalidade: "Adorável, Implacável, Vaidosa",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Héspera.jpeg",
        nome: "Clônia",
        titulo: "Segundo de Héspera",
        ascendencia: "Héspera",
        linhagem: "Maximus",
        dominio: "Ninfa da Primavera",
        elemento: "Madeira",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Corajosa, Leal, Companheira",
    },   
    {
        imagem: "../images/NPC/hera/Terceira Héspera.jpeg",
        nome: "Darkness",
        titulo: "Terceiro de Héspera",
        ascendencia: "Héspera",
        linhagem: "Inferni",
        dominio: "Ninfa da Primavera",
        elemento: "Trevas",
        classe: "Bruxa",
        oficio: "Sacerdotiza Lv 10",
        personalidade: "Narcisista, Possessiva, Misteriosa",
    },   
    {
        imagem: "../images/NPC/hera/Princesa Argos.jpeg",
        nome: "Andrômaca",
        titulo: "Principe de Argos",
        ascendencia: "Argos",
        linhagem: "Argeus",
        dominio: "Visão e Hermafrodita",
        elemento: "Luz Violeta",
        classe: "Bardo",
        oficio: "Artista Lv 10",
        personalidade: "Provocador, Dissimulado, Sociopata",
    },  
    {
        imagem: "../images/NPC/hera/Segunda Argos.jpeg",
        nome: "Marpessa",
        titulo: "Segundo de Argos",
        ascendencia: "Argos",
        linhagem: "Argeus",
        dominio: "Visão",
        elemento: "Vento e Fogo",
        classe: "Arqueira",
        oficio: "Caçador Lv 10",
        personalidade: "Séria, Disciplinada, Aventureira",
    },   
    {
        imagem: "../images/NPC/hera/Terceiro Argos.jpeg",
        nome: "Vigilio",
        titulo: "Terceiro de Argos",
        ascendencia: "Argos",
        linhagem: "Argeus",
        dominio: "Visão e Estratégia",
        elemento: "Prata",
        classe: "Ladino",
        oficio: "Espião Lv 10",
        personalidade: "Leal, Confiante, Honrado",
    },   
];