export const herfesto = [
    {
        imagem: "../images/NPC/herfesto/Principe Herfesto.jpeg",
        nome: "Celestrion",
        titulo: "Principe de Herfesto",
        ascendencia: "Herfesto",
        linhagem: "Windwhisper",
        dominio: "Tempestade",
        elemento: "Raio",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Paquerador, Orgulhoso, Companheiro",
    },  
    {
        imagem: "../images/NPC/herfesto/Segundo Herfesto.jpeg",
        nome: "Amélia",
        titulo: "Segunda Herfesto",
        ascendencia: "Herfesto",
        linhagem: "Vulcan",
        dominio: "Tecnologia e Metal",
        elemento: "Metal",
        classe: "Mago Lv 0",
        oficio: "Engenheira Lv 5",
        personalidade: "Diligente, Criativa, Aproveitadora",
    },    
    {
        imagem: "../images/NPC/herfesto/Principe Brontes.jpeg",
        nome: "Aiolos",
        titulo: "Principe de Brontes",
        ascendencia: "Brontes",
        linhagem: "Perseu",
        dominio: "Juventude e Fogo",
        elemento: "Flama",
        classe: "Espadachim",
        oficio: "Militar Lv 9",
        personalidade: "Franqueza, Leal, Falador",
    },  
    {
        imagem: "../images/NPC/herfesto/Segundo Brontes.jpeg",
        nome: "Adonis",
        titulo: "Segundo de Brontes",
        ascendencia: "Brontes",
        linhagem: "Maximus",
        dominio: "Fogo",
        elemento: "Vento e Terra",
        classe: "Lutador",
        oficio: "Militar Lv 5",
        personalidade: "Servo, Malicioso, Cruel",
    },   
    {
        imagem: "../images/NPC/herfesto/Terceiro Brontes.jpeg",
        nome: "Heberia",
        titulo: "Terceiro de Brontes",
        ascendencia: "Brontes",
        linhagem: "Maximus",
        dominio: "Fartura",
        elemento: "Água e Terra",
        classe: "Bardo",
        oficio: "Copeira Lv 10",
        personalidade: "Diligente, Compreensiva, Gentil",
    },   
    {
        imagem: "../images/NPC/herfesto/Principe Hestia.jpeg",
        nome: "Zopyros",
        titulo: "Principe de Hestia",
        ascendencia: "Hestia",
        linhagem: "Perseus",
        dominio: "Vento e Ninfa do Vento",
        elemento: "Tempestade",
        classe: "Feiticeiro",
        oficio: "Arcanista Lv 9",
        personalidade: "Herói, Altruista, Atrapalhado",
    },  
    {
        imagem: "../images/NPC/herfesto/Segundo Hestia.jpeg",
        nome: "Menelaos",
        titulo: "Segundo de Hestia",
        ascendencia: "Hestia",
        linhagem: "Windwhisper",
        dominio: "Vento",
        elemento: "Água e Fogo",
        classe: "Mago",
        oficio: "Arcanista Lv 10",
        personalidade: "Ingrato, Sério, Anti-social",
    },   
    {
        imagem: "../images/NPC/herfesto/Terceiro Hestia.jpeg",
        nome: "Jason",
        titulo: "Terceiro de Hestia",
        ascendencia: "Hestia",
        linhagem: "Windwhisper",
        dominio: "Oxigênio",
        elemento: "Água",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 7",
        personalidade: "Companheiro, Leal, Servo",
    },   
    {
        imagem: "../images/NPC/herfesto/Principe Ignea.jpeg",
        nome: "Cadmus",
        titulo: "Principe de Ignea",
        ascendencia: "Ignea",
        linhagem: "Maximus",
        dominio: "Força e Resistência",
        elemento: "Metal",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Sério, Orgulhoso, Ignorante",
    },  
    {
        imagem: "../images/NPC/herfesto/Segundo Ignea.jpeg",
        nome: "Charon",
        titulo: "Segundo de Ignea",
        ascendencia: "Ignea",
        linhagem: "Maximus",
        dominio: "Destreza",
        elemento: "Metal",
        classe: "Lutador",
        oficio: "Artista Marcial Lv 10",
        personalidade: "Antipático, Orgulhoso, Protetor",
    },   
    {
        imagem: "../images/NPC/herfesto/Terceiro Ignea.jpeg",
        nome: "Atalanta",
        titulo: "Terceiro de Ignea",
        ascendencia: "Ignea",
        linhagem: "Maximus",
        dominio: "Carisma",
        elemento: "Som",
        classe: "Bardo",
        oficio: "Dançarina Lv 10",
        personalidade: "Narcisista, Franqueza, Gulosa",
    },   
];
