
export const posseidon = [
    {
        imagem: "../images/NPC/posseidon/Principe Posseidon.jpeg",
        nome: "Belerofonte",
        titulo: "Principe de Posseidon",
        ascendencia: "Posseidon",
        linhagem: "Atlante",
        dominio: "Água e Tritão",
        elemento: "Sísmico",
        classe: "Lanceiro",
        oficio: "Militar Lv 10",
        personalidade: "Protetor, Impiedoso, Provocador",
    },   
    {
        imagem: "../images/NPC/posseidon/Segundo Posseidon.jpeg",
        nome: "Evadne", //Gêmea do Principe
        titulo: "Segundo de Posseidon",
        ascendencia: "Posseidon",
        linhagem: "Atlante",
        dominio: "Água e Tritão",
        elemento: "Resistência",
        classe: "Bastião",
        oficio: "Explorador Lv 10",
        personalidade: "Provocador, Curiosa, Vaidosa",
    },   
    {
        imagem: "../images/NPC/posseidon/Principe Tritao.jpeg",
        nome: "Epopeu", //Primo do Príncipe
        titulo: "Principe de Tritão",
        ascendencia: "Tritão",
        linhagem: "Belerofontis",
        dominio: "Tritão",
        elemento: "Resistência e Água",
        classe: "Espadachim",
        oficio: "Militar Lv 10",
        personalidade: "Simplista, Justiceiro, Mulherengo",
    },  
    {
        imagem: "../images/NPC/posseidon/Segundo Tritao.jpeg",
        nome: "Cromos",
        titulo: "Segundo de Tritão",
        ascendencia: "Tritão",
        linhagem: "Aquasoul",
        dominio: "Tritão",
        elemento: "Metal e Água",
        classe: "Druida",
        oficio: "Militar Lv 10",
        personalidade: "Arrogante, Provocador, Disciplinado",
    },   
    {
        imagem: "../images/NPC/posseidon/Terceiro Tritao.jpeg",
        nome: "Náuplio",
        titulo: "Terceiro de Tritão",
        ascendencia: "Tritão",
        linhagem: "Aquasoul",
        dominio: "Tritão",
        elemento: "Água e Vento",
        classe: "Lutador",
        oficio: "Militar Lv 10",
        personalidade: "Arrogante, Desobediente, Pavio Curto",
    },     
    {
        imagem: "../images/NPC/posseidon/Princesa Nereu.jpeg",
        nome: "Caribdis",
        titulo: "Principe de Nereu",
        ascendencia: "Nereu",
        linhagem: "Deep",
        dominio: "Transformação e Tritão",
        elemento: "Tinta",
        classe: "Bruxa",
        oficio: "Ocultista Lv 10",
        personalidade: "Ninfomaníaca, Provocadora, Misteriosa",
    },  
    {
        imagem: "../images/NPC/posseidon/Segundo Nereu.jpeg",
        nome: "Eumolpo",
        titulo: "Segundo de Nereu",
        ascendencia: "Nereu",
        linhagem: "Deep",
        dominio: "Transformação",
        elemento: "Tinta",
        classe: "Bruxo",
        oficio: "Ocultista Lv 10",
        personalidade: "Desconfiado, Traiçoeiro, Misterioso",
    },   
    {
        imagem: "../images/NPC/posseidon/Terceiro Nereu.jpeg",
        nome: "Escila",
        titulo: "Terceiro de Nereu",
        ascendencia: "Nereu",
        linhagem: "Deep",
        dominio: "Transformação",
        elemento: "Veneneo",
        classe: "Bruxa",
        oficio: "Ocultista Lv 10",
        personalidade: "Psicopata, Sem Noção, Obediente",
    },   
    {
        imagem: "../images/NPC/posseidon/Princesa Aqueloo.jpeg",
        nome: "Andrômeda",
        titulo: "Principe de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "Aquasoul",
        dominio: "Aqua e Oráculo",
        elemento: "Gelo e Vapor",
        classe: "Feiticeira Lv 1",
        oficio: "Arcanista Lv 10",
        personalidade: "Independente, Estudiosa, Honrada",
    },  
    {
        imagem: "../images/NPC/posseidon/Segundo Aqueloo.jpeg",
        nome: "Halimede",
        titulo: "Segundo de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "Atlante",
        dominio: "Ninfa da Água",
        elemento: "Fluido",
        classe: "Feiticeira",
        oficio: "Artista Lv 10",
        personalidade: "Inocente, Obediente, Apaixonada",
    },   
    {
        imagem: "../images/NPC/posseidon/Terceiro Aqueloo.jpeg",
        nome: "Quione",
        titulo: "Terceiro de Aqueloo",
        ascendencia: "Aqueloo",
        linhagem: "Aquasoul",
        dominio: "Liquido",
        elemento: "Chama Fria",
        classe: "Maga",
        oficio: "Arcanista Lv 10",
        personalidade: "Séria, Estudiosa, Leal",
    },      
];
